name: Create envfile

on: [push]

jobs:

  create-envfile:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
	  	envkey_DEBUG: false
        envkey_PORT: ${{ secrets.PORT }}
		envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
		envkey_SESION_SECRET: ${{ secrets.SESION_SECRET }}
		envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
		envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
		envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
		envkey_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
		envkey_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
		envkey_FOLDER_IMAGE: ${{ secrets.FOLDER_IMAGE }}
		envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
		envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
		directory: /
        file_name: .env