# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["main"]

jobs:
	create-envfile:
	
		runs-on: self-hosted
	
		steps:
		- name: Make envfile
		uses: SpicyPizza/create-envfile@v1.3
		with:
			envkey_DEBUG: false
			envkey_PORT: ${{ secrets.PORT }}
			envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
			envkey_SESION_SECRET: ${{ secrets.SESION_SECRET }}
			envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
			envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
			envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
			envkey_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
			envkey_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
			envkey_FOLDER_IMAGE: ${{ secrets.FOLDER_IMAGE }}
			envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
			envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
			directory: /
			file_name: .env
			fail_on_empty: false
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm i
            - run: pm2 restart korny
